[package]
name = "dcc"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
heapless = "0.9.1"

defmt = { version = "1.0.1", optional = true }
bytemuck = "1.23.2"
int-enum = "1.2.0"
motor = { path = "../motor"}

[dev-dependencies]
motor = { path = "../motor", features = ["debug"] }

[features]
default = [
]

verbose-transport = []

defmt = [
    "dep:defmt",
    "heapless/defmt",
    "motor/defmt"
]
